### ISSUE TITLE
Conform to ofxAddonsTemplate.

### ISSUE THREAD

**Issue by bakercp** [jvcleave/OpenNI2AppExample#1]
In order to get this repo into ofxAddonsTemplate shape, I had to do a lot of moving stuff around.  Then I changed the repo name and may have broken some stuff.

Can you make an attempt to pull from this fork?

https://github.com/bakercp/ofxOpenNI2Grabber

The RPI stuff isn't finished testing yet, but OSX is working.

**Comment by jvcleave** [comment]
kinda resurrecting this as I am playing with the Orbbec on the RPI

new version is here but currently RPI only - I may change the name in order to avoid confusion
https://github.com/jvcleave/ofxOpenNI2Grabber
